# Generated by Django 5.2.9 on 2026-02-11 04:15

import apps.epg.fields
import django.db.models.deletion
from django.db import migrations, models


def create_extension(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")

class Migration(migrations.Migration):

    dependencies = [
        ("epg", "0021_epgsource_priority"),
    ]

    operations = [
        migrations.RunPython(create_extension, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="epgdata",
            name="embedding_dirty",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="EPGEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", apps.epg.fields.SafeVectorField(dimensions=384)),
                (
                    "epg",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="epg.epgdata",
                    ),
                ),
            ],
        ),
    ]
